title: Builder Development
description: A website.
theme: just-the-docs

url: https://keatonbuilder.github.io/builds/

aux_links:
  GitHub Repository: https://github.com/builderdevelopment/builderdevelopment
  Discord: https://discord.com/QWWRSnJWrY

search_enabled: false

color_scheme: dark

logo: "assets/img/icons/dark-1.1-initial.png"